const data = {
  products: [
    {
        name: 'Slim Shirt',
        slug: 'slim-shirt',
        category: 'Shirts',
        image: '/images/img.jpg',
        price: 90,
        brand: 'Raymond',
        rating: 2.5,
        numReviews: 10,
        countInStock: 0,
        description: 'A popular shirt',
      },
      {
        name: 'Slim Shirt',
        slug: 'slim-shirt1',
        category: 'Shirts',
        image: '/images/img1.jpg',
        price: 90,
        brand: 'Raymond',
        rating: 3.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt2',
      category: 'Shirts',
      image: '/images/img.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/img1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/img.jpg',
      price: 95,
      brand: 'Zara',
      rating: 1.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/img1.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
        name: 'Fit Pants',
        slug: 'fit-pants',
        category: 'Pants',
        image: '/images/img.jpg',
        price: 95,
        brand: 'Zara',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
      {
        name: 'Classic Pants',
        slug: 'classic-pants',
        category: 'Pants',
        image: '/images/img1.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
  ],
};
export default data;